spring.application.name: lloyd-restful-service
server:
  port: 8088

logging:
  level:
    org.springframework: debug

spring:
  message:
    basename: messages

#  security:
#    user:
#      name: lloyd
#      password: 1234

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"

